---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - app/**
  - config/**
  - lib/**
exclude_paths:
- spec/**/*
- test/**/*
- features/**/*
- vendor/**/*
- log/*
- tmp/*
